# Generated by Django 3.2.5 on 2021-08-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='from_ser',
            new_name='from_user',
        ),
    ]
